### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by apatidar0** [czanoli/AI-Mental-Fatigue-Detection-Project#1]
can yo provide link to the dataset

**Comment by czanoli** [comment]
Hi, unfortunately, I can't provide the specific data used for this project as it is proprietary to the University of Modena and Reggio Emilia. However, the code is quite flexible, so with minor adjustments, it should work with other datasets. In any case, the overall pipeline remains the same :)

**Comment by czanoli** [comment]
Hi, unfortunately, I can't provide the specific data used for this project as it is proprietary to the University of Modena and Reggio Emilia. However, the code is quite flexible, so with minor adjustments, it should work with other datasets. In any case, the overall pipeline remains the same :)
